<?php

namespace App\Constants;

/**
 * Message Codes cho hệ thống KhoiTriSo API
 * Định nghĩa các mã thông báo để hỗ trợ đa ngôn ngữ
 */
class MessageCode
{
    // ===== SUCCESS MESSAGES =====
    const SUCCESS = 'SUCCESS';
    const CREATED_SUCCESS = 'CREATED_SUCCESS';
    const UPDATED_SUCCESS = 'UPDATED_SUCCESS';
    const DELETED_SUCCESS = 'DELETED_SUCCESS';

    // ===== AUTH MESSAGES =====
    const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
    const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
    const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
    const EMAIL_VERIFIED_SUCCESS = 'EMAIL_VERIFIED_SUCCESS';
    const PROFILE_UPDATED_SUCCESS = 'PROFILE_UPDATED_SUCCESS';
    const PROFILE_RETRIEVED_SUCCESS = 'PROFILE_RETRIEVED_SUCCESS';

    // ===== USER MESSAGES =====
    const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
    const USER_UPDATED_SUCCESS = 'USER_UPDATED_SUCCESS';
    const USER_DELETED_SUCCESS = 'USER_DELETED_SUCCESS';
    const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
    const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';

    // ===== COURSE MESSAGES =====
    const COURSE_CREATED_SUCCESS = 'COURSE_CREATED_SUCCESS';
    const COURSE_UPDATED_SUCCESS = 'COURSE_UPDATED_SUCCESS';
    const COURSE_DELETED_SUCCESS = 'COURSE_DELETED_SUCCESS';
    const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';
    const COURSE_DETAIL_SUCCESS = 'COURSE_DETAIL_SUCCESS';
    const COURSE_ENROLLED_SUCCESS = 'COURSE_ENROLLED_SUCCESS';

    // ===== LESSON MESSAGES =====
    const LESSON_CREATED_SUCCESS = 'LESSON_CREATED_SUCCESS';
    const LESSON_UPDATED_SUCCESS = 'LESSON_UPDATED_SUCCESS';
    const LESSON_DELETED_SUCCESS = 'LESSON_DELETED_SUCCESS';
    const LESSON_LIST_SUCCESS = 'LESSON_LIST_SUCCESS';
    const LESSON_DETAIL_SUCCESS = 'LESSON_DETAIL_SUCCESS';
    const LESSON_COMPLETED_SUCCESS = 'LESSON_COMPLETED_SUCCESS';

    // ===== BOOK MESSAGES =====
    const BOOK_CREATED_SUCCESS = 'BOOK_CREATED_SUCCESS';
    const BOOK_UPDATED_SUCCESS = 'BOOK_UPDATED_SUCCESS';
    const BOOK_DELETED_SUCCESS = 'BOOK_DELETED_SUCCESS';
    const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS';
    const BOOK_DETAIL_SUCCESS = 'BOOK_DETAIL_SUCCESS';
    const BOOK_ACTIVATED_SUCCESS = 'BOOK_ACTIVATED_SUCCESS';

    // ===== CATEGORY MESSAGES =====
    const CATEGORY_CREATED_SUCCESS = 'CATEGORY_CREATED_SUCCESS';
    const CATEGORY_UPDATED_SUCCESS = 'CATEGORY_UPDATED_SUCCESS';
    const CATEGORY_DELETED_SUCCESS = 'CATEGORY_DELETED_SUCCESS';
    const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
    const CATEGORY_DETAIL_SUCCESS = 'CATEGORY_DETAIL_SUCCESS';

    // ===== ORDER MESSAGES =====
    const ORDER_CREATED_SUCCESS = 'ORDER_CREATED_SUCCESS';
    const ORDER_UPDATED_SUCCESS = 'ORDER_UPDATED_SUCCESS';
    const ORDER_CANCELLED_SUCCESS = 'ORDER_CANCELLED_SUCCESS';
    const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
    const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS';

    // ===== CART MESSAGES =====
    const CART_ITEM_ADDED_SUCCESS = 'CART_ITEM_ADDED_SUCCESS';
    const CART_ITEM_UPDATED_SUCCESS = 'CART_ITEM_UPDATED_SUCCESS';
    const CART_ITEM_DELETED_SUCCESS = 'CART_ITEM_DELETED_SUCCESS';
    const CART_CLEARED_SUCCESS = 'CART_CLEARED_SUCCESS';
    const CART_LIST_SUCCESS = 'CART_LIST_SUCCESS';

    // ===== NOTIFICATION MESSAGES =====
    const NOTIFICATION_CREATED_SUCCESS = 'NOTIFICATION_CREATED_SUCCESS';
    const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS';
    const NOTIFICATION_READ_SUCCESS = 'NOTIFICATION_READ_SUCCESS';
    const NOTIFICATION_DELETED_SUCCESS = 'NOTIFICATION_DELETED_SUCCESS';

    // ===== FORUM MESSAGES =====
    const QUESTION_CREATED_SUCCESS = 'QUESTION_CREATED_SUCCESS';
    const QUESTION_UPDATED_SUCCESS = 'QUESTION_UPDATED_SUCCESS';
    const QUESTION_DELETED_SUCCESS = 'QUESTION_DELETED_SUCCESS';
    const QUESTION_LIST_SUCCESS = 'QUESTION_LIST_SUCCESS';
    const QUESTION_DETAIL_SUCCESS = 'QUESTION_DETAIL_SUCCESS';

    // ===== CERTIFICATE MESSAGES =====
    const CERTIFICATE_GENERATED_SUCCESS = 'CERTIFICATE_GENERATED_SUCCESS';
    const CERTIFICATE_LIST_SUCCESS = 'CERTIFICATE_LIST_SUCCESS';
    const CERTIFICATE_DETAIL_SUCCESS = 'CERTIFICATE_DETAIL_SUCCESS';

    // ===== ERROR MESSAGES =====
    // Validation Errors
    const VALIDATION_ERROR = 'VALIDATION_ERROR';
    const INVALID_EMAIL = 'INVALID_EMAIL';
    const INVALID_PASSWORD = 'INVALID_PASSWORD';
    const INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER';

    // Authentication Errors
    const UNAUTHORIZED = 'UNAUTHORIZED';
    const FORBIDDEN = 'FORBIDDEN';
    const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
    const TOKEN_INVALID = 'TOKEN_INVALID';
    const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';

    // Resource Errors
    const NOT_FOUND = 'NOT_FOUND';
    const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
    const USER_NOT_FOUND = 'USER_NOT_FOUND';
    const COURSE_NOT_FOUND = 'COURSE_NOT_FOUND';
    const LESSON_NOT_FOUND = 'LESSON_NOT_FOUND';
    const BOOK_NOT_FOUND = 'BOOK_NOT_FOUND';
    const CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND';
    const ORDER_NOT_FOUND = 'ORDER_NOT_FOUND';
    const CART_ITEM_NOT_FOUND = 'CART_ITEM_NOT_FOUND';

    // Business Logic Errors
    const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';
    const ALREADY_ENROLLED = 'ALREADY_ENROLLED';
    const COURSE_FULL = 'COURSE_FULL';
    const LESSON_NOT_AVAILABLE = 'LESSON_NOT_AVAILABLE';
    const INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE';
    const INVALID_ACTIVATION_CODE = 'INVALID_ACTIVATION_CODE';
    const ACTIVATION_CODE_ALREADY_USED = 'ACTIVATION_CODE_ALREADY_USED';
    const CART_EMPTY = 'CART_EMPTY';
    const ORDER_CANNOT_CANCEL = 'ORDER_CANNOT_CANCEL';

    // System Errors
    const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
    const DATABASE_ERROR = 'DATABASE_ERROR';
    const EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR';
    const FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR';
    const PRESIGNED_URL_GENERATED = 'PRESIGNED_URL_GENERATED';

    // Rate Limiting
    const RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
    const TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';
}

